version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties
    versions:
    - "< 3, >= 2.a"
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.1
    - 2.4.2
    - 2.4.3
  - dependency-name: org.jfrog.buildinfo:build-info-extractor-gradle
    versions:
    - 4.18.3
    - 4.20.0
  - dependency-name: com.github.kt3k.coveralls
    versions:
    - 2.10.2
